@startuml Anular incidencia
title Diagrama de Actividad: Anular Incidencia (CU-04)
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

' Carriles
|#Pink|Colaborador Operativo|
start
:Se encuentra en la vista "Detalle de Incidencia";
note right
  Precondición: Haber ingresado 
  desde "Consultar Incidencias" (CU-02)
end note

:Presiona el botón "Anular Incidencia";
:Confirma la acción en el mensaje emergente;

|#LightBlue|Sistema|
:Recuperar ID de la incidencia;
:Consultar **Estado Actual** en Base de Datos;

' Decisión Crítica: State Guard (Guardia de Estado)
if (¿El estado es "PENDIENTE"?) then (No)
    ' Flujo de Error: El supervisor ya la tocó
    :Bloquear operación;
    :Mostrar Error: "No se puede anular.\nLa incidencia ya está En Proceso o Cerrada.";
    stop
else (Sí)
    ' Flujo Correcto: Aún está a tiempo
    :Cambiar Estado a **"ANULADO"**;
    :Registrar fecha y hora de anulación;
    
    ' Auditoría: Guardar quién lo anuló
    :Generar registro en Log de Auditoría;
    note right
      Importante: El registro NO se borra de la BD,
      solo se oculta de los reportes activos.
    end note
endif

:Notificar éxito al usuario;
:Actualizar la vista (recargar estado);

|Colaborador Operativo|
:Visualizar el nuevo estado "ANULADO";
stop

@enduml