@startuml Registrar_Incidencia_Actividad cu03
skinparam activity {
    BackgroundColor<<Colaborador Operativo>> Pink
    BackgroundColor<<Sistema>> LightBlue
    BorderColor Black
    FontSize 12
    FontName Arial
}
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle
title Diagrama de Actividad: Registrar Incidencia (CU-03)

' Definición de Carriles
|#Pink|Colaborador Operativo|
start
:Accede a la opción "Nueva Incidencia";

|#LightBlue|Sistema|
' Paso Crítico: No se puede escribir en blanco.
' El sistema debe guiar al usuario con categorías predefinidas.
:Consultar Catálogo de Tipos de Incidencia;
:Mostrar Formulario de Registro;
note right
  Tipos: Infraestructura, Insumos,
  Conflicto Laboral, Cliente, Otros.
end note

|Colaborador Operativo|
repeat
    :Seleccionar Categoría (Obligatorio);
    :Ingresar Título y Descripción Detallada;

    ' Sub-flujo de Evidencia (Opcional pero con validación técnica)
    if (¿Desea adjuntar evidencia?) then (Sí)
        :Seleccionar archivo local (Foto/Video);
        
        |Sistema|
        :Validar archivo (Tipo y Peso);
        
        if (¿Es válido?) then (No)
            :Mostrar error "Archivo muy pesado o formato inválido";
            :Limpiar selección de archivo;
            ' El usuario regresa al loop para corregir o seguir sin archivo
        else (Sí)
            :Marcar archivo como "Listo para subir";
        endif
    else (No)
        |Sistema|
        ' No hace nada
    endif

    |Colaborador Operativo|
    :Presionar botón "Registrar";

    |Sistema|
    :Validar todos los campos obligatorios;

repeat while (¿Faltan datos?) is (Sí) -> Mostrar alertas

' Camino Feliz: Guardado
:Generar Fecha y Hora del Servidor;
:Establecer Estado inicial = **"PENDIENTE"**;
:Guardar registro en Base de Datos;
:Guardar archivo en Servidor (si existe);

' Acciones paralelas (Sistema)
fork
    :Generar Código Único (ej: INC-8842);
fork again
    ' Notificación automática para que el problema no sea ignorado
    :Enviar Alerta al Supervisor de Área;
end fork

:Mostrar mensaje de éxito con el Código generado;
stop

@enduml