@startuml Universidad
title La Universidad Nacional del Valle
!theme blueprint
skinparam dpi 80
skinparam linetype ortho
skinparam ranksep 60
skinparam nodesep 80
left to right direction
hide circle

' --- Entidades Principales ---
entity "Facultad" as Facultad {
  + **código_facultad** (PK)
  --
  nombre
  decano
  presupuesto_anual
}

entity "Programa" as Programa {
  + **código_programa** (PK)
  --
  nombre
  numero_créditos
  coordinador
  código_facultad [FK]
}

entity "Asignatura" as Asignatura {
  + **código_asignatura** (PK)
  --
  nombre
  número_créditos
  horas_semanales
  código_programa [FK]
}

entity "Profesor" as Profesor {
  + **código_profesor** (PK)
  --
  nombre_completo
  especialización
  años_experiencia
  salario
}

entity "Estudiante" as Estudiante {
  + **código_estudiante** (PK)
  --
  nombre_completo
  fecha_nacimiento
  dirección
  teléfono
}

' --- Entidades Asociativas (Relaciones N:M) ---

' N:M entre Profesor y Facultad
entity "Adscripcion" as Adscripcion {
  + **id_adscripcion (PK)**
  --
  + código_profesor (FK)
  + código_facultad (FK)
}

' N:M entre Estudiante y Programa
entity "Adscripcion" as Adscripcion {
  + **id_adscripcion (PK)**
  --
  + código_profesor (FK)
  + código_facultad (FK)
}
' N:M entre Profesor y Asignatura
entity "Imparte" as Imparte {
  + **id_imparte (PK)**
  --
  + código_profesor (FK)
  + código_asignatura (FK)
  semestre
}

' N:M entre Estudiante y Asignatura
entity "Matricula" as Matricula {
  + **id_matricula (PK)**
  --
  + código_estudiante (FK)
  + código_asignatura (FK)
  semestre
  nota_obtenida
}


' --- Relaciones 1:N ---
Facultad "1" -- "0..*" Programa : ofrece
Asignatura "0..*" -- "1" Programa : pertenece_a

' --- Conexiones a Entidades Asociativas (N:M) ---
Profesor "1..*" -- "0..*" Adscripcion : trabaja_en
Facultad "1..*" -- "0..*" Adscripcion : tiene

Estudiante "1..*" -- "0..*" Inscripcion : se_inscribe_en
Programa "1..*" -- "0..*" Inscripcion : tiene

Profesor "1..*" -- "0..*" Imparte : imparte
Asignatura "1..*" -- "0..*" Imparte : es_impartida_por

Estudiante "1..*" -- "0..*" Matricula : cursa
Asignatura "1..*" -- "0..*" Matricula : es_cursada_por
' --- Relaciones Ocultas ---
Facultad -[hidden]-> Programa
Programa -[hidden]-> Asignatura
Profesor -[hidden]-> Facultad
Estudiante -[hidden]-> Programa

@enduml