@startuml  Consulta Log de Auditoría - Caso de Uso
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

actor "Administrador" as Admin

package "Seguridad y Auditoría" {
    
    usecase "Consultar Log de Auditoría" as UC_Audit
    
    ' Funcionalidades Críticas
    usecase "Filtrar por Actor/Evento" as UC_FilterAudit
    usecase "Ver 'Snapshot' (Valor Antes/Después)" as UC_Snapshot
    usecase "Exportar Log (Compliance)" as UC_ExportLog

    ' Relación Principal
    Admin -- UC_Audit

    ' Relaciones de Extensión
    ' El log suele ser enorme. Filtrar es casi obligatorio para usarlo, pero técnicamente es una extensión de la vista principal.
    UC_Audit <.. UC_FilterAudit : <<Extiende>>

    ' Ver qué cambió exactamente (Ej: El sueldo era 100, ahora es 200)
    UC_Audit <.. UC_Snapshot : <<Extiende>>

    ' Exportar para auditorías externas o legales
    UC_Audit <.. UC_ExportLog : <<Extiende>>
}
@enduml