@startuml   Dashboard de Carga - Caso de Uso
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

actor "Supervisor de Área" as Sup

package "Gestión de Operaciones y Carga" {
    
    usecase "Visualizar Dashboard de Carga" as UC_Dash
    
    ' Funcionalidades de apoyo al análisis
    usecase "Filtrar por Rol/Turno" as UC_Filter
    usecase "Ver Métricas de Estrés" as UC_Metricas
    
    ' La ACCIÓN que soluciona el problema de Kung Food Panda
    usecase "Redistribuir Tareas/Personal" as UC_Reasignar

    ' Relación Principal
    Sup -- UC_Dash

    ' 1. INCLUDE: El dashboard se construye en base a métricas. 
    ' Al abrir el dashboard, el sistema YA calculó las métricas.
    UC_Dash ..> UC_Metricas : <<Incluye>>

    ' 2. EXTEND: Filtros. A veces quiero ver solo "Cocineros" o solo "Meseros".
    UC_Dash <.. UC_Filter : <<Extiende>>

    ' 3. EXTEND (Crítico): La toma de decisión.
    ' Si veo el dashboard en rojo, procedo a reasignar gente.
    UC_Dash <.. UC_Reasignar : <<Extiende>>
}

@enduml