@startuml Gestion de Usuarios - Sistema SGO-KFP
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

actor "Administrador" as Admin

package "Administración de Personal (CRUD)" {
    
    ' El caso de uso padre (opcional, si quieres agrupar) o las acciones directas
    usecase "Registrar Nuevo Usuario" as UC_Create
    usecase "Modificar Datos/Rol" as UC_Update
    usecase "Desactivar Usuario (Baja Lógica)" as UC_Disable
    usecase "Restablecer Contraseña (Forzado)" as UC_ResetPass

    ' Funcionalidades de Validación
    usecase "Verificar Duplicidad" as UC_CheckDup
    usecase "Asignar Rol y Permisos" as UC_AssignRole

    ' Relaciones Principal
    Admin -- UC_Create
    Admin -- UC_Update
    Admin -- UC_Disable
    Admin -- UC_ResetPass

    ' Lógica Interna
    
    ' Al crear, OBLIGATORIAMENTE asignas un rol (Cocinero, Mozo, Supervisor)
    ' Esto es vital para evitar el problema de "asignación informal" que tenía el restaurante.
    UC_Create ..> UC_AssignRole : <<Incluye>>
    UC_Update ..> UC_AssignRole : <<Incluye>>
    
    ' Al crear, el sistema verifica que el DNI/Correo no exista
    UC_Create ..> UC_CheckDup : <<Incluye>>
    
    ' Nota sobre la Baja Lógica
    note right of UC_Disable
      No se elimina el registro.
      Solo se quita el acceso para
      mantener el historial de incidencias.
    end note
}
@enduml