@startuml   Registrar Incidencia
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

actor "Colaborador Operativo" as Colab

package "Gestión de Reportes" {
    
    usecase "Registrar Nueva Incidencia" as UC_Registrar
    usecase "Seleccionar Categoría" as UC_Categoria
    usecase "Adjuntar Evidencia (Foto/Video)" as UC_Evidencia
    usecase "Notificar a Responsable" as UC_Notificar

    ' Relación principal
    Colab -- UC_Registrar

    ' Relaciones Técnicas
    
    ' 1. INCLUDE: Es imposible registrar una incidencia sin decir de qué tipo es
    ' (Infraestructura, RRHH, Insumos, Cliente). Es un paso obligatorio.
    UC_Registrar ..> UC_Categoria : <<Incluye>>

    ' 2. EXTEND: La evidencia es ideal pero no siempre obligatoria
    ' (a veces es un tema verbal o no tienes cámara a mano).
    UC_Registrar <.. UC_Evidencia : <<Extiende>>

    ' 3. INCLUDE: El sistema DEBE avisar a alguien automáticamente al guardar.
    ' Esto es comportamiento del sistema, pero vale la pena mostrarlo si quieres detalle.
    UC_Registrar ..> UC_Notificar : <<Incluye>>
}
@enduml