@startuml Diagrama de CLases
' Configuración visual
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 100 
skinparam ranksep 100
skinparam classFontSize 12
skinparam classFontName "Arial"
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 5
hide circle

' --- 1. ENTIDADES (SUSTANTIVOS) ---

' Clase Padre
abstract class Usuario {
    - id_usuario : int
    - dni : string
    - nombre : string
    - correo : string
    - password_hash : string
    - estado : enum {ACTIVO, INACTIVO}
    + iniciarSesion()
    + cerrarSesion()
}

class Rol {
    - id_rol : int
    - nombre : string {Admin, Supervisor, Operativo}
    - permisos : json
}

class Incidencia {
    - id_incidencia : int
    - titulo : string
    - descripcion : text
    - fecha_creacion : datetime
    - prioridad : enum {BAJA, MEDIA, ALTA, CRITICA}
    - estado_actual : enum {PENDIENTE, EN_DISPUTA, RESUELTO, ANULADO}
    + registrar()
    + anular()
    + cambiarEstado()
}

class Categoria {
    - id_categoria : int
    - nombre : string {Infraestructura, RRHH, Insumos}
    - sla_horas : int
}

class Evidencia {
    - id_evidencia : int
    - archivo_url : string
    - tipo : enum {IMG, VIDEO, PDF}
    - fecha_subida : datetime
}

class Mesa {
    - id_mesa : int
    - numero : string
    - zona : string {Terraza, Salon, Barra}
}

class Turno {
    - id_turno : int
    - nombre : string {Mañana, Tarde, Noche}
    - hora_inicio : time
    - hora_fin : time
}

' La entidad para la defensa del empleado
class Descargo {
    - id_descargo : int
    - argumento_defensa : text
    - fecha_envio : datetime
    - estado : enum {EN_REVISION, ACEPTADO, RECHAZADO}
    + registrar()
}

' La entidad para auditar (tu "Trazabilidad")
class HistorialEstado {
    - id_historial : int
    - estado_anterior : string
    - estado_nuevo : string
    - fecha_cambio : datetime
    - comentario_sistema : string
}

' --- 2. RELACIONES (VERBOS) ---

' Un Usuario TIENE un Rol
Usuario "1" --> "1" Rol : tiene asignado >

' Un Usuario (Colaborador) REPORTA muchas Incidencias
Usuario "1" -- "0..*" Incidencia : reporta >

' Un Usuario (Supervisor) RESUELVE muchas Incidencias
Usuario "1" -- "0..*" Incidencia : resuelve/gestiona >

' Una Incidencia OCURRE en una Mesa (Tu diagrama original)
Mesa "1" -- "0..*" Incidencia : origina <

' Una Incidencia PERTENECE a una Categoría
Categoria "1" -- "0..*" Incidencia : clasifica <

' Una Incidencia OCURRE durante un Turno (Tu diagrama original)
Turno "1" -- "0..*" Incidencia : sucede durante <

' Una Incidencia CONTIENE Evidencias
Incidencia "1" *-- "0..*" Evidencia : documenta con >

' Relación Crítica: Disputa
' Una Incidencia MOTIVA un Descargo
Incidencia "1" -- "0..1" Descargo : motiva >

' Auditoría
' Una Incidencia GENERA historial (Tu "Ejecuta o Audita")
Incidencia "1" *-- "1..*" HistorialEstado : genera traza en >
Usuario "1" -- "0..*" HistorialEstado : provoca >

@enduml